[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "coxph"
version = "1.0.0"
description = "Federated algorithm for Cox proportional hazards model"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = [
    "v6-federated-algo-core-py @ https://github.com/mdw-nl/v6-federated-algo-core-v6/archive/c29dd63f40c6e3997a0865cb0cbc81dd9ce02a60.tar.gz",
    "pydantic>=2,<3",
    "vantage6-client>=4.13.3",
    "vantage6-algorithm-tools>=4.13.1",
    "numpy",
    "pandas",
    "scipy",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4",
]

[project.urls]
Homepage = "https://github.com/MaastrichtU-CDS/v6-coxph"

[tool.setuptools.packages.find]
include = ["coxph*"]
